customize:
  redis:
    redisson:
      config:
        test: 1
        ##单机
  #      singleServerConfig:
  #        address: redis://192.168.3.222:6379
  #        code: org.redisson.codec.JsonJacksonCodec
        ##主从
        masterSlaveServersConfig:
          masterAddress: redis://192.168.2.222:6379
          slaveAddresses: redis://192.168.2.222:6380



